title: ChrisOboes Blog
email: blog@oboe.email
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog about stuff that interests me and stuff where i think
  it may help others. It will mainly contain content about Linux
  distributions and other open source software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
reddit_username: ChrisOboe
github_username:  ChrisOboe

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
